name: Build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: skylyrac/blocksds:slim-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: make

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DS81
          path: |
            ds81*.nds
            CHANGES
            COPYING
            instructions.txt
            README
